language: php
sudo: required
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

matrix:
  fast_finish: true

env:
  matrix:
    - PREFER_LOWEST="" WITH_COVERAGE="--coverage-clover=coverage.xml"
    - PREFER_LOWEST="--prefer-lowest" $WITH_COVERAGE=""

before_script:
#    - composer self-update
    - composer update --prefer-source $PREFER_LOWEST

script:
  - ./bin/phpunit --configuration tests/phpunit.xml $WITH_COVERAGE

after_success:
  - bash <(curl -s https://codecov.io/bash)
